// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using ERP.Helper.Models;
//
//    var responseExternalServiceModel = ResponseExternalServiceModel.FromJson(jsonString);

namespace ERP.Helper.Models
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseExternalServiceModel<T>
    {
        [JsonProperty("isTrue")]
        public bool IsTrue { get; set; }

        [JsonProperty("data")]
        public T Data { get; set; }

        [JsonProperty("message")]
        public string Message { get; set; }

        [JsonProperty("error")]
        public string Error { get; set; }
    }

    public partial class ResponseExternalServiceModel<T>
    {
        public static ResponseExternalServiceModel<T> FromJson(string json) => JsonConvert.DeserializeObject<ResponseExternalServiceModel<T>>(json, ERP.Helper.Models.Converter.Settings);
    }
}
