// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using ERP.Helper.Models;
//
//    var smtpSendRequestModel = SmtpSendRequestModel.FromJson(jsonString);

namespace ERP.Helper.Models
{
    using System;
    using System.Collections;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class SmtpSendRequestModel
    {
        [JsonProperty("to")]
        public string To { get; set; }

        [JsonProperty("subject")]
        public string Subject { get; set; }

        [JsonProperty("body")]
        public string Body { get; set; }
        [JsonProperty("files")]
        public List<SmtpSendRequestModel_File> Files { get; set; } = null;
    }

    public partial class SmtpSendRequestModel_File
    {
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("typeFile")]
        public string TypeFile { get; set; }

        [JsonProperty("base64")]
        public string Base64 { get; set; }
    }

    public partial class SmtpSendRequestModel
    {
        public static SmtpSendRequestModel FromJson(string json) => JsonConvert.DeserializeObject<SmtpSendRequestModel>(json, ERP.Helper.Models.Converter.Settings);
    }

    public partial class SmtpSendRequestModel
    {
        public object ToObject()
        {
            return new
            {
                to = To,
                subject = Subject,
                body = Body,
                files = Files == null ? null : Files.Select(x => (object)new
                {
                    x.Name,
                    x.Base64,
                    x.TypeFile,
                }).ToList(),
            };
        }


        public SmtpSendRequestModel FromObject(object data)
        {
            return JsonConvert.DeserializeObject<SmtpSendRequestModel>(JsonConvert.SerializeObject(data));
        }
    }
}
