// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using ERP.Helper.Models;
//
//    var smtpSendRequestModel = SmtpSendRequestModel.FromJson(jsonString);

namespace ERP.Helper.Models
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class SmtpSendRequestModel
    {
        [JsonProperty("to")]
        public string To { get; set; }

        [JsonProperty("subject")]
        public string Subject { get; set; }

        [JsonProperty("body")]
        public string Body { get; set; }
    }

    public partial class SmtpSendRequestModel
    {
        public static SmtpSendRequestModel FromJson(string json) => JsonConvert.DeserializeObject<SmtpSendRequestModel>(json, ERP.Helper.Models.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this SmtpSendRequestModel self) => JsonConvert.SerializeObject(self, ERP.Helper.Models.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
